apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          - "api.${OCP4_DOMAIN}"
        servingCertificate:
          name: api-tls
